config/routes.rb
Rails.application.routes.draw do
  resources :datos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "datos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dato.rb
class Dato < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/datos_controller.rb
class DatosController < ApplicationController
  before_action :set_dato, only: %i[ show edit update destroy ]

  # GET /datos or /datos.json
  def index
    @datos = Dato.last(500)
  end

  # GET /datos/1 or /datos/1.json
  def show
  end

  # GET /datos/new
  def new
    @dato = Dato.new
  end

  # GET /datos/1/edit
  def edit
  end

  # POST /datos or /datos.json
  def create
    @dato = Dato.new(dato_params)

    respond_to do |format|
      if @dato.save
        format.html { redirect_to dato_url(@dato), notice: "Dato was successfully created." }
        format.json { render :show, status: :created, location: @dato }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datos/1 or /datos/1.json
  def update
    respond_to do |format|
      if @dato.update(dato_params)
        format.html { redirect_to dato_url(@dato), notice: "Dato was successfully updated." }
        format.json { render :show, status: :ok, location: @dato }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos/1 or /datos/1.json
  def destroy
    @dato.destroy

    respond_to do |format|
      format.html { redirect_to datos_url, notice: "Dato was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dato
      @dato = Dato.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dato_params
      params.require(:dato).permit(:modulo, :sensor1, :sensor2, :sensor3, :sensor4, :sensor5, :sensor6, :sensor7, :sensor8, :sensor9, :sensor10, :sensor11, :sensor12, :sensor13, :sensor14, :sensor15, :sensor16, :sensor17, :sensor18, :sensor19, :sensor20, :sensor21, :comentarios)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datos_helper.rb
module DatosHelper
end

app/views/datos/_dato.html.erb
<div id="<%= dom_id dato %>">
<p>
    <strong>Modulo:</strong>
    <%= dato.modulo %>
  </p>
  <p>
    <strong>sensor1:</strong>
    <%= dato.sensor1 %>
  </p>

  <p>
    <strong>sensor2:</strong>
    <%= dato.sensor2 %>
  </p>

  <p>
    <strong>sensor3:</strong>
    <%= dato.sensor3 %>
  </p>

  <p>
    <strong>sensor4:</strong>
    <%= dato.sensor4 %>
  </p>

  <p>
    <strong>sensor5:</strong>
    <%= dato.sensor5 %>
  </p>

  <p>
    <strong>sensor6:</strong>
    <%= dato.sensor6 %>
  </p>
  <p>
    <strong>sensor7:</strong>
    <%= dato.sensor7 %>
  </p>
  <p>
    <strong>sensor8:</strong>
    <%= dato.sensor9 %>
  </p>
  <p>
    <strong>sensor9:</strong>
    <%= dato.sensor9 %>
  </p>
  <p>
    <strong>sensor10:</strong>
    <%= dato.sensor10 %>
  </p>
  <p>
    <strong>sensor11:</strong>
    <%= dato.sensor11 %>
  </p>
  <p>
    <strong>sensor12:</strong>
    <%= dato.sensor12 %>
  </p>
  <p>
    <strong>sensor13:</strong>
    <%= dato.sensor13 %>
  </p>
  <p>
    <strong>sensor14:</strong>
    <%= dato.sensor14 %>
  </p>
  <p>
    <strong>sensor15:</strong>
    <%= dato.sensor15 %>
  </p>
  <p>
    <strong>sensor16:</strong>
    <%= dato.sensor16 %>
  </p>
  <p>
    <strong>sensor17:</strong>
    <%= dato.sensor17 %>
  </p>
  <p>
    <strong>sensor18:</strong>
    <%= dato.sensor18 %>
  </p>


</div>

app/views/datos/_form.html.erb
<%= form_with(model: dato) do |form| %>
  <% if dato.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dato.errors.count, "error") %> prohibited this dato from being saved:</h2>

      <ul>
        <% dato.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Modulo, style: "display: block" %>
    <%= form.text_field :modulo %>
  </div>

  <div>
    <%= form.label :Sensor_1_temp_celcius, style: "display: block" %>
    <%= form.number_field :sensor1 %>
  </div>
  <div>
    <%= form.label :Sensor_2_temp_celcius, style: "display: block" %>
    <%= form.number_field :sensor2 %>
  </div>
  <div>
    <%= form.label :Sensor_3_temp_celcius, style: "display: block" %>
    <%= form.number_field :sensor3 %>
  </div>
  <div>
    <%= form.label :Sensor_4_temp_celcius, style: "display: block" %>
    <%= form.number_field :sensor4 %>
  </div>
  <div>
    <%= form.label :Sensor_5_temp_celcius, style: "display: block" %>
    <%= form.number_field :sensor5 %>
  </div>
  <div>
    <%= form.label :Sensor_6_temp_celcius, style: "display: block" %>
    <%= form.number_field :sensor6 %>
  </div>
  <div>
    <%= form.label :Sensor_7_humedad, style: "display: block" %>
    <%= form.number_field :sensor7 %>
  </div>
  <div>
    <%= form.label :Sensor_8_corriente, style: "display: block" %>
    <%= form.number_field :sensor8 %>
  </div>
  <div>
    <%= form.label :Sensor_9_corriente, style: "display: block" %>
    <%= form.number_field :sensor9 %>
  </div>
  <div>
    <%= form.label :Sensor_10_corriente, style: "display: block" %>
    <%= form.number_field :sensor10 %>
  </div>
  <div>
    <%= form.label :Sensor_11_psi, style: "display: block" %>
    <%= form.number_field :sensor11 %>
  </div>
  <div>
    <%= form.label :Sensor_12_psi, style: "display: block" %>
    <%= form.number_field :sensor12 %>
  </div>
  <div>
    <%= form.label :Sensor_13_vibración, style: "display: block" %>
    <%= form.number_field :sensor13 %>
  </div>
  <div>
    <%= form.label :Sensor_14_alarma, style: "display: block" %>
    <%= form.number_field :sensor14 %>
  </div>
  <div>
    <%= form.label :Sensor_15_alarma, style: "display: block" %>
    <%= form.number_field :sensor15 %>
  </div>
  <div>
    <%= form.label :Sensor_16_alarma, style: "display: block" %>
    <%= form.number_field :sensor16 %>
  </div>
  <div>
    <%= form.label :Sensor_17_alarma, style: "display: block" %>
    <%= form.number_field :sensor17 %>
  </div>
  <div>
    <%= form.label :Sensor_18_alarma, style: "display: block" %>
    <%= form.number_field :sensor18 %>
  </div>




  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/datos/edit.html.erb
<h1>Editing dato</h1>

<%= render "form", dato: @dato %>

<br>

<div>
  <%= link_to "Ver dato", @dato %> |
  <%= link_to "Volver a datos", datos_path %>
</div>

app/views/datos/index.html.erb
<h1>Reporte</h1>

<div class="container">
 <div class="row">
  <div class="col-sm-2">
    <div class="card bg-light shadow">
      <div class="card-body">
        <h5 class="card-title">Temp ambiente</h5>
        <% if @datos.any? && @datos.last.sensor6.present? %>
          <p class="card-text text-center display-6 text-primary"><%= @datos.last.sensor6.round(0) %></p>
        <% else %>
          <p class="card-text text-center display-6 text-primary">No data</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-2">
    <div class="card bg-light shadow">
      <div class="card-body">
        <h5 class="card-title">Humedad</h5>
        <% if @datos.any? && @datos.last.sensor7.present? %>
          <p class="card-text text-center display-6 text-primary"><%= @datos.last.sensor7.round(0) %></p>
        <% else %>
          <p class="card-text text-center display-6 text-primary">No data</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-2">
    <div class="card bg-light shadow">
      <div class="card-body">
        <h5 class="card-title">Corriente</h5>
        <% if @datos.any? && @datos.last.sensor8.present? %>
          <p class="card-text text-center display-6 text-primary"><%= @datos.last.sensor8.round(0) %></p>
        <% else %>
          <p class="card-text text-center display-6 text-primary">No data</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-2">
    <div class="card bg-light shadow">
      <div class="card-body">
        <h5 class="card-title">Corriente</h5>
        <% if @datos.any? && @datos.last.sensor9.present? %>
          <p class="card-text text-center display-6 text-primary"><%= @datos.last.sensor9.round(0) %></p>
        <% else %>
          <p class="card-text text-center display-6 text-primary">No data</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-2">
    <div class="card bg-light shadow">
      <div class="card-body">
        <h5 class="card-title">Corriente</h5>
        <% if @datos.any? && @datos.last.sensor10.present? %>
          <p class="card-text text-center display-6 text-primary"><%= @datos.last.sensor10.round(0) %></p>
        <% else %>
          <p class="card-text text-center display-6 text-primary">No data</p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>
  <div class="row">
    <div class="col-sm-10 card bg-light shadow">
      <%= line_chart [
        {name: 'Sensor 1 Temp', data: Dato.pluck(:created_at, :sensor1)},
        {name: 'Sensor 2 Temp', data: Dato.pluck(:created_at, :sensor2)},
        {name: 'Sensor 3 Temp', data: Dato.pluck(:created_at, :sensor3)},
        {name: 'Sensor 4 Temp', data: Dato.pluck(:created_at, :sensor4)},
        {name: 'Sensor 5 Temp', data: Dato.pluck(:created_at, :sensor5)}
      ], height: '300px' %>
    </div>
  </div>
<br>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
       <div id="chart_div" style="width: 400px; height: 120px;"></div>


<br>
<br>
<div class="row">
    <div class="col-sm-6">
<table id="myTable" class="table table-striped table-bordered shadow table-bordered m-3" style="width: 1200px;">

  <thead>
    <tr>
      <th>Creado</th>
      <th>Modulo</th>
      <th>Temp 1 °C</th>
      <th>Temp 2 °C</th>
      <th>Temp 3 °C</th>
      <th>Comentarios</th>


      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @datos.each do |dato| %>
      <tr id="<%= dom_id dato %>">
        <td><%= dato.created_at %></td>
        <td><%= dato.modulo %></td>
        <td><%= dato.sensor1 %></td>
        <td><%= dato.sensor2 %></td>
        <td><%= dato.sensor3 %></td>
        <td><%= dato.comentarios %></td>


        <td>
  <%= link_to dato, class: "btn btn-primary btn-sm" do %>
    <i class="bi bi-eye"></i>
  <% end %>
  <%= link_to edit_dato_path(dato), class: "btn btn-secondary btn-sm" do %>
    <i class="bi bi-pencil"></i>
  <% end %>
  <%= link_to dato, method: :delete, data: { confirm: "Esta seguro?" }, remote: true, class: "btn btn-danger btn-sm" do %>
    <i class="bi bi-trash"></i>
  <% end %>
</td>
      </tr>
    <% end %>
  </tbody>
</table>
 </div>
  </div>



<%= link_to "Agregar dato", new_dato_path,  class: "btn btn-primary" %>



<link href="https://cdn.datatables.net/v/bs5/jq-3.6.0/jszip-2.5.0/dt-1.13.4/b-2.3.6/b-colvis-2.3.6/b-html5-2.3.6/b-print-2.3.6/date-1.4.1/r-2.4.1/sb-1.4.2/datatables.min.css" rel="stylesheet"/>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/v/bs5/jq-3.6.0/jszip-2.5.0/dt-1.13.4/b-2.3.6/b-colvis-2.3.6/b-html5-2.3.6/b-print-2.3.6/date-1.4.1/r-2.4.1/sb-1.4.2/datatables.min.js"></script>


<script type="text/javascript">

$(document).ready(function() {
    var table = $('#myTable').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'excel',
            'csv',
            'print',
            'pdf',
            'copy'
        ],
         language: {
    url: "../es-ES.json",
  },



    } );
} );


 google.charts.load('current', {'packages':['gauge']});
google.charts.setOnLoadCallback(drawChart);

function drawChart() {

  var data = google.visualization.arrayToDataTable([
    ['Label', 'Value'],
    ['Presión', <%= @datos.last.sensor11.nil? ? 30 : @datos.last.sensor11 %>],
    ['Presión', <%= @datos.last.sensor11.nil? ? 50 : @datos.last.sensor11 %>],
    ['Vibración', <%= @datos.last.sensor11.nil? ? 70 : @datos.last.sensor11 %>]
  ]);

  var options = {
    width: 400, height: 120,
    redFrom: 90, redTo: 100,
    yellowFrom:75, yellowTo: 90,
    minorTicks: 5
  };

  var chart = new google.visualization.Gauge(document.getElementById('chart_div'));

  chart.draw(data, options);

  // set fixed values for each data point
  data.setValue(0, 1, 80);
  data.setValue(1, 1, 55);
  data.setValue(2, 1, 68);
  chart.draw(data, options);

}

</script>

<style>


</style>

app/views/datos/new.html.erb
<h1>Nuevo dato</h1>

<%= render "form", dato: @dato %>

<br>

<div>
  <%= link_to "Back to datos", datos_path %>
</div>

app/views/datos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dato %>

<div>
  <%= link_to "Edit this dato", edit_dato_path(@dato) %> |
  <%= link_to "Back to datos", datos_path %>

  <%= button_to "Destroy this dato", @dato, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iotesla</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="m-3 p-3">
   <%= yield %>
  </div>


  </body>
</html>